import 'dart:convert';
import 'package:flutter/services.dart';
import '../../routing/conditions.dart';
import '../../routing/network.dart';
import '../models/shop.dart';

/// Published closures plus when they were transcribed from calgary.ca.
class ClosureFeed {
  final List<Closure> closures;
  final String retrieved;
  final String sourceUrl;
  const ClosureFeed(this.closures, this.retrieved, this.sourceUrl);
}

class MapDataSource {
  Plus15Network? _network;
  ClosureFeed? _closures;
  List<Shop>? _shops;

  /// The routing network generated by tool/build_network.dart.
  Future<Plus15Network> loadNetwork() async {
    if (_network != null) return _network!;
    // Decode on this isolate: loadString() hands >50 KB files to compute(),
    // which never runs under widget tests' fake async. ~500 KB takes a few ms.
    final bytes = await rootBundle.load('assets/data/network.json');
    final raw = utf8.decode(bytes.buffer.asUint8List(bytes.offsetInBytes, bytes.lengthInBytes));
    return _network = Plus15Network.fromJson(json.decode(raw) as Map<String, dynamic>);
  }

  Future<ClosureFeed> loadClosures() async {
    if (_closures != null) return _closures!;
    final raw = json.decode(await rootBundle.loadString('assets/data/closures.json'))
        as Map<String, dynamic>;
    return _closures = ClosureFeed(
      [
        for (final c in raw['closures'] as List)
          Closure.fromJson(c as Map<String, dynamic>)
      ],
      raw['retrieved'] as String? ?? '',
      raw['sourceUrl'] as String? ?? '',
    );
  }

  Future<List<Shop>> loadShops() async {
    if (_shops != null) return _shops!;
    final raw = await rootBundle.loadString('assets/data/shops.json');
    final list = json.decode(raw) as List;
    _shops = list.map((e) => Shop.fromJson(e)).toList();
    return _shops!;
  }
}
